version: '3.8'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/admin
      - SECRET_KEY=your-secret-key-here
    depends_on:
      - mongodb
    volumes:
      - .:/app
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/ad
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: